#SERVER-CFG
server:
  port: 8282

#MONGO-CFG
spring:
  data:
    mongodb:
      port: 27017
      uri: mongodb://localhost:27017/doto
      database: doto

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
